CREATE TABLE `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `password_resets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `token` VARCHAR(255) NOT NULL UNIQUE,
  `expires_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `files` (
  `id` CHAR(36) NOT NULL, -- Assuming UUID v4, generated by backend
  `user_id` INT UNSIGNED NOT NULL,
  `parent_id` CHAR(36) NULL,
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('file', 'folder') NOT NULL,
  `mime_type` VARCHAR(100) NULL,
  `size` BIGINT UNSIGNED NULL,
  `server_filename` VARCHAR(255) NOT NULL, -- Unique filename on server (e.g., UUID.ext or original sanitized name if unique handling is robust)
  `server_folder_path` VARCHAR(1024) NOT NULL, -- Path to the directory on server where the file/folder resides, relative to a user's root upload dir
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`parent_id`) REFERENCES `files`(`id`) ON DELETE CASCADE,
  INDEX `idx_files_user_id` (`user_id`),
  INDEX `idx_files_parent_id` (`parent_id`),
  INDEX `idx_files_name_parent_id_user_id` (`user_id`, `parent_id`, `name`) -- For unique constraints per folder per user
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add a unique constraint to prevent duplicate names within the same folder for the same user
-- This needs to handle NULL parent_id for root items.
-- For MySQL, a functional index or a more complex unique index might be needed if truly enforcing uniqueness with NULLs.
-- A simpler approach is to handle this constraint at the application level or use a placeholder for NULL parent_id in the unique key.
-- For now, application-level check is assumed for (name, parent_id, user_id) uniqueness.

-- The `server_path` from previous iteration is split into `server_filename` and `server_folder_path` for clarity.
-- `server_filename` is the actual name of the file on disk (could be original or a UUID).
-- `server_folder_path` is the path to the directory containing this item, relative to the user's root upload directory.
-- Example: user's root: /srv/uploads/user_123/
-- A file "report.pdf" in "Documents" folder:
-- name: "report.pdf"
-- server_filename: "uuid_for_report.pdf" (or "report.pdf" if handled carefully)
-- server_folder_path: "Documents/" (path relative to user's root)
-- A folder "Documents":
-- name: "Documents"
-- server_filename: "Documents" (name of the directory on disk)
-- server_folder_path: "" (if it's in the user's root) or "ParentFolder/" if nested.

-- For folders, `mime_type` and `size` will be NULL.
-- For folders, `server_filename` will be the name of the directory on the disk.
-- The full path to an item on disk would be: BASE_UPLOAD_PATH/USER_ID_SUBDIR/server_folder_path/server_filename
